## Cleaning 7th Variable for Naive Bayes

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Loading Merged Data and New data
merged = pd.read_csv("/Users/kendallgilbert/dsan-5000-project-kendallgilbert180/dsan-website/5000-website/data/01-modified-data/merged.csv")
pi_nb = pd.read_csv("/Users/kendallgilbert/dsan-5000-project-kendallgilbert180/dsan-website/5000-website/data/00-raw-data/naive_bayes_policy.csv")

In [7]:
new_header = pi_nb.iloc[0] #Grabbing the first row for the header
pi_nb = pi_nb[1:] #Taking the data less the header row
pi_nb.columns = new_header #Setting the header row as the df header
pi_nb = pi_nb.rename(columns={'Year': 'Country'})
pi_nb

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,Australia,10.64,9.62,9.09,9.26,8.93,8.62,8.33,7.94,8,...,6.82,6.59,6.74,6.82,6.82,6.59,6.52,6.52,6.52,6.52
2,Austria,3.85,3.85,3.85,3.85,3.85,3.7,3.7,3.57,3.57,...,3.45,3.45,3.45,3.45,3.45,3.45,3.45,3.45,3.45,3.33
3,Belgium,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Canada,5.23,4.94,4.6,4.49,4.42,4.04,4.31,4.35,4.35,...,4.37,4.37,4.37,4.37,4.37,4.37,4.35,4.35,4.35,4.35
5,Chile,19.05,22.73,22.73,22.73,22.73,20.83,19.23,17.24,16.67,...,18.18,20,24.32,24.32,23.68,23.68,23.68,23.68,23.68,23.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Uganda,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
131,Ukraine,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
132,Uruguay,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
133,Venezuela,..,..,..,..,..,..,..,..,..,...,..,..,..,..,..,0,0,0,0,..
134,Viet Nam,66.67,66.67,66.67,66.67,66.67,75,75,75,75,...,80,80,80,80,80,80,80,80,83.33,87.5

In [8]:
#Melting Data
melted_policy = pd.melt(pi_nb, id_vars=['Country'], var_name='Year', value_name='Value')

# Convert the "Year" column to a string and then combine "Country" and "Year" into "Country_Year"
melted_policy['Country_Year'] = melted_policy['Country'] + '_' + melted_policy['Year'].astype(str)

# Drop the original "Country" and "Year" columns
melted_policy = melted_policy.drop(columns=['Country', 'Year'])

# Convert the "Year" column to a string and then combine "Country" and "Year" into "Country_Year"
merged['Country_Year'] = merged['Country'] + '_' + merged['Year'].astype(str)

# Drop the original "Country" and "Year" columns
merged = merged.drop(columns=['Country', 'Year'])

nb_record = pd.merge(merged, melted_policy, on='Country_Year', how='inner')

In [9]:
import numpy as np
# Split 'Country_Year' into 'Country' and 'Year'
nb_record[['Country', 'Year']] = nb_record['Country_Year'].str.split('_', expand=True)
# Drop the original 'Country_Year' column
nb_record = nb_record.drop('Country_Year', axis=1)

In [10]:
#Exporting as CSV
nb_record.to_csv("nb_record.csv", header=True, index=False)